name: 'update releases on public repo'
on:
    workflow_dispatch:

    release:
        types: [published]
jobs: 
  update-release:
    permissions:
        contents: write
    runs-on: ubuntu-20.04
    steps:
        - name: update releases on public repo
          uses: andrewthetechie/gha-clone-releases@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            src_repo: MeetMo/grout-desktop-app
